# Generated by Django 3.0.14 on 2021-07-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
