# Generated by Django 3.0.14 on 2021-07-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_combo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
